version: '3.9'

services:
    app:
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: password

    db:
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
        volumes:
            - db-data:/var/lib/mysql

    redis:
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

volumes:
    db-data:
    redis-data:
